### ISSUE TITLE
Cocktail Party

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#10]

**Comment by marc-hanheide** [comment]
OK, so we need an example fragment of the JSON structure to go in for persons and objects. Can @iocchi or @andreavanzo provide the skeleton? And then @robpinillos adds what he'll provide?

**Comment by iocchi** [comment]
Check relation between personID from PeoplePerception and faceID from FaceDetection/FaceRecognition

**Comment by marc-hanheide** [comment]
We will statr with a dummy object recognition action, and maybe later @robpinillos and swap this out for an actual action using the NaoQi Object recogniser.
