### ISSUE TITLE
SPR

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#13]

**Comment by andreavanzo** [comment]
I've implemented most of the interactions of the task. We need to agree on which information (and the sharing format) we can get from the vision module (e.g., size of the crowd, number of males and females, sitting people...) when analysing the crowd.

**Comment by marc-hanheide** [comment]
I think we might just need an action `analyzecrowd`, that just looks around and try to get as much information from the people and populate a JSON data structure:
```
{
  `people`: [
    'id': 12342134,
    'gender': 'male'
  ]
}

**Comment by robpinillos** [comment]
Memorize people
==================
Writes in ALMemory 'Actions/memorizepeople/PeopleList/' array with peoplelist 
Writes in 'Actions/memorizepeople/Person/IDNUMBER' for each person detected the json data
IDNUMBER for now is the same as the personid provided by naoqi PeopleDetected.

result

```

 {
		"personid": 1,
    "person_naoqiid": 10592, 
    "info": {
      "shirtcolor": {
        "hsv": [
          -1.0, 
          -1.0, 
          -1.0
        ], 
        "name": "Purple"
      },  
      "height": 1.80, 
			"posture": "unknow", 
  	}, 
		"lastlocation": {
		  "world": {
		    "y": 0.0, 
		    "x": 0.0
		  }, 
		  "topological": {
		    "current_node": "TODO", 
		    "closest_node": "TODO"
		  }
		}, 
		"face_naoqi": {
		  "name": "Roberto",
      "faceinfo": {
				  "gender": {
				    "conf": 1.0, 
				    "val": "male"
				  }, 
				  "age": {
				    "conf": 0.4, 
				    "val": 40.0
				  },
				  "smile": {
				    "conf": 0.16, 
				    "val": 0.05
				  },
					"expression": "" 
      } 
		},
		"face_ms_api": {
		  "name": "Roberto",
      "faceinfo": {
				  "gender": {
				    "val": "male"
				  }, 
				  "age": {
				    "val": 40.0
				  },
				  "smile": {
				    "val": 0.05
				  },
					"hair": {
				    "color": "brown",
						"conf": 0.9
				  },
					"facialhair": {
				    "Moustache": 0.0,
				    "Beard": 0.0,
				    "Sideburns": 0.0
				  },
					"glasses": "ReadingGlasses",
				  "accessories": [
				    {
				      "type": "glasses",
				      "confidence": 0.99
				    }
				  ],
					"emotion": "" 
      } 
		}
	}



```

**Comment by marc-hanheide** [comment]
`TopologicalNav/CurrentNode`
`TopologicalNav/ClosestNode`

They raise events when changed

**Comment by robpinillos** [comment]
There was incoherence between name of memory in the actions `memorypeople` and `memoryface`
Finally
`Actions/MemorizePeople/PeopleList/`
 `Actions/MemorizePeople/Person/<IDNUMBER>`

Btw Do you know how to delete all the data from:  `Actions/MemorizePeople/Person/<IDNUMBER#1>`,`Actions/MemorizePeople/Person/<IDNUMBER#2>`,
`Actions/MemorizePeople/Person/<IDNUMBER#3>`  prevously created?

**Comment by robpinillos** [comment]
A little reminder about the info from each person. the info provided by Microsoft API  `age` and `gender` would be more reliable  (`face_ms_api` ) than the naoqi driver (`face_naoqi`). But the `face_ms_api` is only available after face learning ( It needs a face close to the robot)
