### ISSUE TITLE
Poster Session Poster

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#19]
Scored on
* Novelty Scientific contribution
* Relevance for RoboCup@HOME
* Presentation

**Comment by marc-hanheide** [comment]
looking for ideas to what to include: What are the main scientific contributions?
* clearly nav (reference to paper) und speech

Please post ideas @iocchi @mtlazaro @sergimolina @pet1330 @robpinillos

**Comment by marc-hanheide** [comment]
We may reuse this poster for the symposium, needs a good title

**Comment by iocchi** [comment]
filled Planning & Execuion section. PNP of RIPS plan is included. If too difficult to read, we can put the plan and the ER instead.

**Comment by mtlazaro** [comment]
Filled Navigation.
We should put photo of the Pepper maybe in the middle of all blocks, I've just left a picture there.

**Comment by sergimolina** [comment]
Unfortunately, there are no novel contributions for the people perception since we are using Pepper API in the end :(
