### ISSUE TITLE
tablet actions

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#21]
use cases for tablet:

- start/stop task
- display speech output
- a general debugging display area for the tasks
- possibly: display answer options, ideally as a button, needs to interact with slu4r @andreavanzo

**Comment by marc-hanheide** [comment]
some progress, the backend is working, needs integration with actions and some actual useful content. @andreavanzo is there a memory entry in `ALmemory` that contains the last utterance the robot said, so I can use display it on the screen?

**Comment by andreavanzo** [comment]
sure! the entry key is named "Veply" (yes, it is supposed to be Reply, but the V is for Vanzo :D ). you just need to subscribe to that event

**Comment by marc-hanheide** [comment]
Cool, I'll display that on the screen!

Another question @andreavanzo: 

Can i also "inject" a speech recognition into the dialog? My plan is to provide a speech_fake action that displays answers on the screen to shortcut actually saying them. In case speech recognition doesn't work as an implementation of the RoboCup CONTINUE rule.

**Comment by andreavanzo** [comment]
But how do you choose the possible candidate answers?

**Comment by marc-hanheide** [comment]
I was about to ask you 😉. The simplest solution would be a `offeranswerui` action with parameters for the options to be put in the plan before a dialog action. But I'm open to better ideas.

**Comment by marc-hanheide** [comment]
Any suggestions? Or i implement my simple one.

**Comment by marc-hanheide** [comment]
@andreavanzo @iocchi could you let me know how to inject the speech?

**Comment by andreavanzo** [comment]
Hi @marc-hanheide sorry for the delay. I think the best solution is just to raise a new event, say "TabletAnswer" for the key and the selected answer as value. The dialogue module will subscribe to such event and handle the sentence properly.  This also let us to distinguish among sentences spoken by the user and those input from the tablet. Let me know if you agree

**Comment by marc-hanheide** [comment]
Sounds good to me. I shall do that and then get back to you. Have you got any idea how I could know which utterances are expected? I will just create ab action for now of the format `speechbtn_btn1_btn2_btn2` where I replace any `%` with space, e.g. `speechbtn_yes_no_can%I%have%a%beer%please`. I hope this is compatible with the action parameter format, is it @iocchi ?

**Comment by marc-hanheide** [comment]
I'll make it listen also for `AnswerOptions` to display options coming from dialog.

**Comment by marc-hanheide** [comment]
I have implemented both `AnswerOptions` and `TabletAnswer` as discussed above in 39a9543fc94abd7d3d877abf2670ccb75883578f

@andreavanzo The UI will react to a string of the format `"speechbtn_yes_no%it is not_third%option"` raised in `AnswerOptions` and render this as 

![image](https://user-images.githubusercontent.com/1153084/28476019-5e905a32-6e46-11e7-86a2-815c19867f32.png)

When one of the buttons is clicked, the text displayed is raised as an event on `TabletAnswer`.

*note:* If you just write `speechbtn` without any parameters, all will be removed.

**Comment by marc-hanheide** [comment]
I have now also implemented the action `speechbtn`. Tested with 

`./action_cmd.py -a speechbtn -p "option_yes_no%it is not_third%option" -c start`

will display the three buttons as in [previous comment](https://github.com/LCAS/spqrel_tools/issues/21#issuecomment-317070425)

`./action_cmd.py -a speechbtn  -c start`

will remove them.

The action always returns successfully, immediately. It can hence, be included into any plan without any bigger side effects.

The action is implemented in fea8414ceea3df6a281a0b5509e56b7310976480

**Comment by marc-hanheide** [comment]
tidied this all a bit more and used the "usual" action scheme. Looks final now.

**Comment by iocchi** [comment]
@marc-hanheide  Need to reopen this issue because `#` and ` ` are not allowed in PNP. It works with action_cmd, but it won't work when the plan is translated in PNP. You can use `+` instead.
Example:  `speechbtn_yes_no+it+is+not_third+option`

**Comment by marc-hanheide** [comment]
I used `%` and not `#`. I tried it and it worked fine. So, is that ok?

**Comment by iocchi** [comment]
did you try to write this in a plan file, generate a pnml and execute it?

**Comment by marc-hanheide** [comment]
Yes, whole tool chain, blockly->plan->pnml>naoqi_pnp. Worked just fine.

**Comment by iocchi** [comment]
I get something strange with `%` that I do not understand: the plan seems to be correctly executed, but pnp_naoqi complains about a PNP condition with these symbols. While with `+` this does not happen.

```
%parsing failed on condition: (speechbtn_yes_no_can%I%have.finished) 
```
I am not sure I'll have time to look into it. I suggest to use `+` I trust this situation better...

**Comment by marc-hanheide** [comment]
OK, we shall move to `+` then.
