### ISSUE TITLE
[PNP] timeouts of actions

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#23]

**Comment by iocchi** [comment]
Done

TODO: add documentation about how to use them.
At the moment see `test3` example in [PNPnaoqi/plans](https://github.com/iocchi/PetriNetPlans/tree/master/PNPnaoqi/plans)

**Comment by iocchi** [comment]
How to use timeouts described in
[PNPnaoqi/README](https://github.com/iocchi/PetriNetPlans/blob/master/PNPnaoqi/README.txt)
