### ISSUE TITLE
Disable ASR by default when speech modules are loaded

### ISSUE THREAD

**Issue by iocchi** [LCAS/spqrel_tools#29]
Let's define and use an memory variable  `ASREnabled`   initialized to false.

**Comment by andreavanzo** [comment]
Fixed. The key of the ALMemory event is called `ASR_enable`

**Comment by andreavanzo** [comment]
By default the ASR is disabled. Whenever `1` is published on `ASR_enable` (as integer), the ASR is enable. On the contrary, when `0` is published, the ASR is disabled.
