### ISSUE TITLE
Flex error on 14.04

### ISSUE THREAD

**Issue by iocchi** [LCAS/spqrel_tools#32]
The problem is that naoqi distribution does not include flex.
So I manually added file `FlexLexer.h` in `PNPnaoqi\include` (16.04 version)
You can try to replace this file with the 14.04 version (`/usr/include/FlexLexer.h`)
Maybe we can try in transforming this file in a symbolic link.

**Comment by marc-hanheide** [comment]
Yes, it works with a symlink. But why is it needed in the first place, we cross-compile on a system where the headers are available, so, why do they have to be copied in?

**Comment by iocchi** [comment]
I agree that it is not needed (it was a quick fix that I even forgot about...) probably we just need to add the include dir in CMakeLists file

**Comment by marc-hanheide** [comment]
Indeed. Trying it now.

**Comment by marc-hanheide** [comment]
see https://github.com/iocchi/PetriNetPlans/pull/20 works!
