### ISSUE TITLE
blockly onto Pepper

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#34]
put https://github.com/LCAS/robot_blockly branch PNP to Pepper

Issues still to solve:

- [ ] launch the execution
- [ ] highlight currently executed action
- [ ] make sure it runs in an iframe on the Pepper main UI

**Comment by marc-hanheide** [comment]
can @iocchi define a ALmemory slot that just contains the currently executed action.

**Comment by marc-hanheide** [comment]
In explanation to the above, can this be made an ALMemory slot, that just contains the action name, and its parameters, e.g. `goto_bar`, and that this slot is made empty (`""`) when no action is executed?

**Comment by iocchi** [comment]
Done the ALMemort slot is `PNP/CurrentAction`
