### ISSUE TITLE
Questions to TC during team leaders meeting

### ISSUE THREAD

**Issue by mtlazaro** [LCAS/spqrel_tools#37]
- [x] Which is the variability in the formulation of the questions of SPR test
- [x] Discuss door pass as requirement to start task

**Comment by marc-hanheide** [comment]
Notes from Meeting 1 (6pm day 1):

* 50% to be promoted to stage 2, 4 teams in SSPL, the TC might increase the number if scores are close.
* final with two teams. One winner in each sub league.
* SSPL will not have a 3rd place as they are not enough
* all finals will be in ONE arena together
* there will be a schedule for individual testing slots (20-30 minutes)
* (*not for us*) OPL will only have 2 attempts for each test (but 3 for storing groceries)
* **ignore the web schedule**, new schedule to be released today, first will be SPR
* network discussion:
  * a lot of people require network
  * they consider the wifi too slow
  * the TC is pretty clear that no cable is allowed and that we have to live with the limited capacity
* there will be schedule also for the inspection
* volunteers need to be there 15 minutes before test, there is a penalty, TC will allocate team volunteers
* the two best of the 3 attempts count
* external microphones are allowed, but detail is very limited

**Comment by marc-hanheide** [comment]
Notes from Meeting 2: 9pm Wednesday

* SPR crowd is only composed of people in the arena
* SPR: questions will only be asked once unless the robot asks to repeat
* HMC: robots will go into the audience
* if you are not ready, you are back to the end of the queue
* for the HRI award, we should approach the TC and make them aware if we want to apply. Should we present the blockly interaction interface @iocchi? at least other teams I talked to liked it.
* about 10am some industry visitors are coming
* we should put things into the storage room

**Comment by marc-hanheide** [comment]
# Meeting 3:

* in GPSR for SSPL no need to come back to starting position. Allowed to receive command at the position where it completed the last command
* talk to Softbank about the shortcomings of Pepper
* report on Pepper is sought after also by trustees

* for restaurant:
  * for SSPL we can replace manipulation with assistance.
  

# General suggestions for TC

* in the future, allow contingencies, where the professional actor is asked to perform a specific action to allow to continue. After every contingency is applied, all points awarded afterwards to be halved, also for every following contingency again.
* provide food!
