### ISSUE TITLE
robot status UI

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#39]
to display:

- [x] current plan
- [x] current action
- [ ] temperature
- [x] battery

**Comment by iocchi** [comment]
current action stored in memory with key `PNP/CurrentAction`
current plan in `PNP/CurrentPlan`

**Comment by marc-hanheide** [comment]
Are you raising events for those? Polling is not really efficient and also not following the event-driven pattern I use throughout ;-)

**Comment by marc-hanheide** [comment]
I can't see this yet, did you commit and push?

**Comment by iocchi** [comment]
Now they are events. Pushed into PNP repo.
For the CurrentPlan you need to recompile since it is in pnp_naoqi.cpp
CurrentAction is set in action_base.py

**Comment by marc-hanheide** [comment]
works! Thanks, @iocchi 

Only comment: The `PNP/CurrentAction` isn't emptied at the end of a plan. It would be better if it would raise a `""` content event at the end of an action, but that's not critical.

**Comment by marc-hanheide** [comment]
Current status:

![image](https://user-images.githubusercontent.com/1153084/28489918-fbf1903c-6ec5-11e7-9d37-314e52f007dc.png)

**Comment by marc-hanheide** [comment]
@iocchi I don't know the key for Temperature. What should I display? The rest is working fine.

**Comment by iocchi** [comment]
If you use the advanced menu on Pepper, you can read the name of the memory keys for the temperatures.
They are probably also somewhere in the documentation, but I think reading them from Pepper is faster.

**Comment by iocchi** [comment]
Can we start a full test from GUI only? Suppose network is fully unavailable, can we just boot the robot and use the GUI to start a test?
How is logging activated? Can we have a button on the GUI or an action to enable/disable logging from the plan?
