### ISSUE TITLE
do not duplicate pepper_tools

### ISSUE THREAD

**Issue by iocchi** [LCAS/spqrel_tools#4]
I suggest to not duplicate pepper_tools here (wrt Mayte's repo) to avoid confusion.
Let's just use Mayte's pepper_tools for very simple examples (no specific of RoboCup tasks)
and this repo for more advanced tools/programs for the team.

**Comment by mtlazaro** [comment]
I agree with Luca, let's use this repo only for advanced tools and the simple programs that we can write to understand how to use some particular NAOqi module can go to pepper_tools
