### ISSUE TITLE
people memorisation

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#41]
this is to discuss the peculiarities of the people perception.

As needed for #10 in particular and #13.

So far @robpinillos stores the person information in memory, one slot for each person with a unique ID. Does @andreavanzo already read this format or should we make it one larger JSON structure that he keeps updated. At the moment people are *never* deleted.

**Comment by andreavanzo** [comment]
I actually do the same. Whenever the dialogue ends, the name/drink are stored into the variable Humans/ProfileN, where N is an increasing number that identifies the current order (e.g. 1, 2, 3). According to the task, the idea is to acquire perceptual information just after the dialogue. So @robpinillos should read the Humans/ProfileN variables and populate the JSON. What do you think?
