### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by ahmader** [LCAS/spqrel_tools#47]
Hello,
I can see great work you've done here, I am curious if we can collaborate some of Pepper code.

I tried to install and run the spqrel_tools/actions, but failed because of missing `action_base` and `conditions` classes. Any suggestion how to fix this?

Thanks

**Comment by mtlazaro** [comment]
Hi @ahmader,

`action_base` and `conditions` are part of [PetriNetPlans](https://github.com/iocchi/PetriNetPlans).

You can check our [wiki](https://github.com/LCAS/spqrel_tools/wiki) for more details in the use of our software.

Best,
Mayte
