### ISSUE TITLE
Logging data

### ISSUE THREAD

**Issue by iocchi** [LCAS/spqrel_tools#5]
naoqibag utility
INPUT: set of ALMemroy keys, frequency, output file name
OUTPUT: save on the output file name data like: timestamp; key; value for each key in input at the given frequency

**Comment by mtlazaro** [comment]
Developed the tool naoqibag.
It reads a set of keys stored in different files and writes their corresponding values in an output file in a folder containing the current data. Path to this folder can be selected.
Upon request of NAOqibag/EnableCamera with a float value, images from topCamera are also recorded at the selected rate=value. We can decide if we want to record from all cameras but it's a costly operation. 
Recording of audio is managed directly by lu4p.
