### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by iocchi** [LCAS/spqrel_tools#7]
Define a way to initialize parameters in config file(s)

Example:
read config file with <keys,values>
set all the keys with the values

**Comment by marc-hanheide** [comment]
Should we make this one YAML file? 

Should also be used SPR, to define the answers to questions

**Comment by Jailander** [comment]
I have made a script for this is part of this PR: https://github.com/LCAS/spqrel_tools/pull/35

**Comment by Jailander** [comment]
Please check and close issue if happy

**Comment by marc-hanheide** [comment]
Hi, do you think it might be a good idea to include this code that @Jailander produced as part of #35 into my tmux-based launch system (see #28 and https://github.com/LCAS/spqrel_tools/blob/master/tmux/README.md). I would then create a "config" section into https://github.com/LCAS/spqrel_tools/blob/master/tmux/spqrel-pepper-config.json and work through with @Jailander code?

**Comment by marc-hanheide** [comment]
@jailander as I already said in #35 I think something is very wrong with that PR, so I close it. Could you tidy this up to make sure we really only get the changes you want us to have?

**Comment by marc-hanheide** [comment]
Should now be done properly in PR #38

**Comment by marc-hanheide** [comment]
First Implementation is merged. Needs testing

**Comment by marc-hanheide** [comment]
not sure we use it right now, but it worked ;-)
