### ISSUE TITLE
topo map editor

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#8]

**Comment by Jailander** [comment]
The topo map editor is already finished but it needs documentation

**Comment by Jailander** [comment]
is part of this PR: https://github.com/LCAS/spqrel_navigation/pull/2
Documentation here: https://github.com/LCAS/spqrel_navigation/wiki/How-to-use-topological-navigation

**Comment by Jailander** [comment]
I will close this reopen if necessary
