### ISSUE TITLE
Packing List

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#9]
- [ ]  plug adapters (DIAG)
- [ ] plug adapters (LINCOLN)
- [x] Router + switch + 8 eth cables (LINCOLN)
- [ ] Wired mice (DIAG)
- [ ] Wired mice (LINCOLN)
- [x] UK extension lead (LINCOLN)
- [ ] IT extension lead (DIAG)
- [ ] ASUS Xtion (DIAG) 
- [ ] MARRtino (including Hokuyo, joystick and charger) (DIAG)
- [x] T-shirts (LINCOLN)
- [ ] Poster(s)
- [ ] Consent forms signed (DIAG)
- [ ] Consent forms signed (LINCOLN)
- [ ] Long eth cable for robot (DIAG)
- [ ] Video camera (Mayte)

**Comment by iocchi** [comment]
- [ ] Consent forms signed (DIAG)
- [ ] Consent forms signed (LINCOLN)

**Comment by marc-hanheide** [comment]
I'll check in a very large suitcase, which should be big enough for our kit. Plan is that I pack it all Saturday morning when I have the car and pick up everything from the lab, ok @sergimolina ? Does anyone know if laptops are allowed in checked luggage?

**Comment by iocchi** [comment]
laptop in checked luggage: I would say yes 
- any idea about Hokuyo Laser in cabin baggage?

**Comment by marc-hanheide** [comment]
I think it should be fine. If you have it, bring a receipt or something, showing it's a standard device.

**Comment by marc-hanheide** [comment]
I only have one Japan-UK Power Adapter, so if @sergimolina has any, bring them.

**Comment by marc-hanheide** [comment]
Shall I take a big suitcase again, then?

**Comment by marc-hanheide** [comment]
Can the Lincoln team please pile all things to take in one place in the FabLab?

**Comment by mtlazaro** [comment]
I printed consent forms for all, we can signed them there.

**Comment by marc-hanheide** [comment]
@MFernandezCarmona @sergimolina @francescodelduchetto I put some bits from the list in the FabLab.
